### ISSUE TITLE
Problem with سے combination

### ISSUE THREAD

**Issue by NaurozAhmad** [lamerw/Arabic-Converter-From-and-To-Arabic-Presentation-Forms-B#1]
I'm having an issue with the letters سے. The presentation form result breaks س into isolated form whereas it should've been initial form. What am I doing wrong?

Not just سے. there's also نہ. The converter breaks it into ن ہ.

**Comment by NaurozAhmad** [comment]
Found the problem. I was using this plugin for Urdu so first I had to change the character code in charsMap to those provided for Urdu. The rest works perfectly.

**Comment by lamerw** [comment]
@NaurozAhmad, if you provide characters map for Urdu I can extend this library and it will work with two languages
